Development
verenichyi/songbird pull request #1
Opened 2022-03-24 13:26 UTC by verenichyi

2022-04-08 11:05 UTC, julia-dream requested changes
Общие замечания по демо:

Есть невыполненные части задания, было бы круто их сделать: 
1) при выборе правильно ответа проигрывание аудиоплеера должно остановиться
2) у кастомного аудиоплеера есть регулятор громкости звука
3) Поздравление с абсолютной победой, если набрано максимально возможное количество баллов - не могу проверить, в консоль не выведены правильные ответы 

Технические моменты: 
1) Изначально в мастере что-то есть, осложняет проверку
2) Большой размер изображения лого
3) [songbird](https://github.com/verenichyi/songbird/tree/26a57c1e9a1ae4a10c24b9e3b532b160fc96d0ad)constants/interfaces.ts - пустой файл

В целом - замечательная работа, очень понравилась! Буду ждать исправления замечаний :)

2022-04-08 11:05 UTC, julia-dream commented on src/constants/types.ts
> +};
Интерфейс, не тип

2022-04-08 11:05 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +  descriptionBirdID: number | null;
Вместо `number | null` лучше использовать optional fields (их также обычно записывают в конце интерфейса, после обязательных полей)
(https://www.logicbig.com/tutorials/misc/typescript/interface-to-describe-object-with-optional-properties.html)

2022-04-08 11:05 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +  indicators: { id: number; status: string }[];
`currentLevelClickedOptions` - не совсем корректный тип, смотри optional fields
`{ id: number; status: string }` лучше вынести в отдельный интерфейс

2022-04-08 11:05 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +
не хватает модульности - очень хотелось бы интерфейсы/типы в своем файле/папке, константы в своем месте и тд

2022-04-08 11:05 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +        new Set([...state.currentLevelClickedOptions, payload])
насколько здесь необходимо использование Set? в большинстве случаев на практике это костыль при повторяющихся элементах в массиве

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    if (isRightAnswer && currentLevel === 5) {
магическое число, нужно вынести в константу

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +      setIsEndOfQuiz(true);
по большинству конвенций использование предлогов в названиях переменных недопустимо, да и в целом название выглядит не слишком понятно

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    }
оба блока `isMatch` и `isRightAnswer && currentLevel === 5` выходят из функции, хотелось бы как-то объединить эту логику 
`isRightAnswer && currentLevel === 5` было бы неплохо иметь в качестве константы сразу после `isRightAnswer`, это упростит рефакторинг для объединения логики

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    if (!currentLevelClickedOptions.find((opt: number) => opt === id)) {
такие выражения не должны быть в условии

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    if (!currentLevelClickedOptions.find((opt: number) => opt === id)) {
и хотелось бы больше ясности насчет `opt`

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +        setIndicatorStatus({
мне кажется, эта переменная предполагает в себе только статус исходя из названия 
ты же записываешь туда и айдишник тоже

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +      }
туда же в объединение логики

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +      }
в целом слишком много кондишенов для одного коллбэка, нужно рефакторить + выносить небольшие функции 
почитай о SOLID, в текущем случае речь о букве S :)
https://habr.com/ru/company/ruvds/blog/426413/

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +  });
очень просится useMemo

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    </section>
почему бы не добавить ul в `list`?

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/styles.module.scss
> +  margin: 0 12px;
точно-точно нужно именно 12px?

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/styles.module.scss
> +    margin-bottom: 1.5em;
выше margin в пикселях, давай использовать какую-то одну единицу измерения

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Answers/styles.module.scss
> +  display: inline-block;
сейчас уже максимально стараются уходить от использования inline-block

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/App/App.tsx
> +    <div className={'container'}>
className='container'?

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/App/App.tsx
> +      {!isEndOfQuiz ? (
положительный вариант обычно идет сначала

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/App/App.tsx
> +            name={isMatch ? currentLevelQuestionBird.name : mockName}
такие штуки лучше выносить в константы, это позволит тебе и реакту закэшить их в случае необходимости, а не вычислять непосредственно при передаче

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/App/app.scss
> +  margin: 0 -12px;
отрицательный?

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/AudoPlayer/AudioPlayer.tsx
> +    if (audioPlayer.current) {
optional chaining, иначе потом баги вылезут с рефами

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/AudoPlayer/AudioPlayer.tsx
> +    setIsPlaying(!prevValue);
не вижу смысла этой константы :)

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Description/Description.tsx
> +const Description = ({ bird }: { bird: Bird | null }) => {
optional fields

2022-04-08 11:05 UTC, julia-dream commented on src/view/components/Header/Header.tsx
> +  ));
ul, useMemo

2022-04-12 11:49 UTC, verenichyi commented on src/view/components/Answers/Answers.tsx
> +        setIndicatorStatus({
нууу здесь айдишник я записываю в action.payload объект вместе со статусом только для того, чтобы знать у какого точно элемента нужно поменять этот статус

2022-04-12 13:54 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +        setIndicatorStatus({
если уже оставлять эту логику со статусом, то давай тогда поменяем имя переменной (что-нибудь вроде `setIndicatorStatusInfo` хотя бы )

2022-04-14 11:01 UTC, julia-dream requested changes
Класс! Оставила еще несколько замечаний...

2022-04-14 11:01 UTC, julia-dream commented on src/constants/common.ts
> +export const mockName = '******';
Давай попробуем сделать mockName не просто константой, а преобразуем в звездочки все символы строки реального ответа

2022-04-14 11:01 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +  questionBirdID: randomBirdID(6),
Что-то совсем не понятно, что тут происходит 
Если это функция для получения рандомного айди - давай добавим get в название (`getRandomBirdID`)
А что за магическое число 6 передается туда? как минимум его стоит назвать как-то и вынести в константу, как максимум - вообще в функции `getRandomBirdID` не должно быть каких-то входящих статических параметров, это же рандом)

2022-04-14 11:01 UTC, julia-dream commented on src/redux/reducers/songbird.ts
> +  descriptionBirdID: null,
Пока уже давай оставим, но на будущее - у тебя есть два очевидно связанных между собой параметра - `questionBirdID` и ` descriptionBirdID`. Согласись, что было бы гораздо нагляднее держать их вместе в одном объекте, да и обновлять одно поле гораздо проще двух

2022-04-14 11:01 UTC, julia-dream commented on src/utils/helpers.ts
> +  (time < 10 ? `0${time}` : `${time}`);
А что за магическое 10?

2022-04-14 11:01 UTC, julia-dream commented on src/utils/helpers.ts
> +export const randomBirdID = (amount: number) =>
Выше упоминала, это нужно порефакторить

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +    });
`setIndicatorStatusInfo({
      id,
      status,
    });`
 все еще повторяется в обеих функциях

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +      setIsQuizEnded(true);
тут уже или isQuizEnded, или setIsQuizEnd

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +            );
А почему ты вынес ul над useMemo? не совсем понимаю, в чем смысл такой мемоизации?

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Answers/styles.module.scss
> +  width: 49%;
точно-точно именно 49?

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +            );
мы же обсуждали с тобой механизм реконсиляции реакта? как думаешь, при перерендере ул-элемента (он же не входит у нас в useMemo), будут ли перерендериваться дочерние элементы?

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/App/App.tsx
> +    setQuestionBirdID(randomBirdID(6));
где-то выше я уже видела вызов этой функции с таким же параметром 
если уж ты все-таки постоянно используешь какое-то одинаковое значение, то почему бы не записать результат вызова функции в константу и не использовать ее везде?

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/App/App.tsx
> +    setQuestionBirdID(randomBirdID(6));
нет нужды выделять лишние ресурсы на то, чтобы еще раз вызвать функцию, если ее результат будет одинаковым при обоих вызовах

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/App/App.tsx
> +    setQuestionBirdID(randomBirdID(6));
можно еще конечно сделать кэширование для функции, но думаю вариант с константой гораздо проще

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/AudioPlayer/AudioPlayer.tsx
> +  const [volume, setVolume] = useState(0.5);
Магическое число

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Congrats/Congrats.tsx
> +    {score < 30 ? (
Магическое число

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Description/styles.module.scss
> +  width: 49%;
Уже писала про 49

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Header/Header.tsx
> +    </ul>
тоже писала про мемоизацию

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Main/Main.tsx
> +  const birdName = isMatch ? currentLevelQuestionBird.name : mockName;
выглядит как один объект, а не две разные переменные

2022-04-14 11:01 UTC, julia-dream commented on src/view/components/Main/Main.tsx
> +      {currentLevel !== birdsData.length - 1 && (
я, кажется, уже упоминала вычисления в возвращаемых значениях

2022-04-14 12:59 UTC, verenichyi commented on src/redux/reducers/songbird.ts
> +  questionBirdID: randomBirdID(6),
с именем функции реально косяк)
как максимум в этом рандоме через входящий параметр здесь подразумевается какой-то диапазон
но суть не в этом
крч здесь у меня был жесткий затуп
изначально у меня здесь не было вот этой недофункции и рандомное число присваивалось через useEffect каждый раз когда менялся номер вопроса с привязкой к количеству птичек в массиве(и не надо было никакого магического числа)
но потом, когда я начал разбирать комменты, в какой-то момент  заметил жесткий баг(может он и был раньше, но ни я, ни ты этого не замечали)
просидел я часа 3 над этой проблемой и все равно не понимал почему не работает как надо, хотя должно
по итогу переделал на вот эту шляпу

2022-04-14 13:02 UTC, verenichyi commented on src/view/components/Answers/styles.module.scss
> +  width: 49%;
вот хоть убей меня не догоняю почему нет
а вот если точно 49?

2022-04-14 14:45 UTC, verenichyi commented on src/redux/reducers/songbird.ts
> +  descriptionBirdID: null,
не совсем понимаю что ты имеешь в виду
`descriptionBirdID` меняется постоянно при каждом клике на вариант ответа и служит для отображения соответствующего описания в блоке с описанием птички
`questionBirdID` меняется только в случае изменения текущего вопроса и для того, чтобы понимать произошло ли совпадение сравниваются `questionBirdID` с `id` одного из вариантов списка

2022-04-15 08:34 UTC, verenichyi commented on src/redux/reducers/songbird.ts
> +  questionBirdID: randomBirdID(6),
Разобрался :)

2022-04-15 12:07 UTC, julia-dream commented on src/view/components/Answers/styles.module.scss
> +  width: 49%;
мне казалось, что мы уже в каждом твоем предыдущем таске обсудили округление чисел :)

2022-04-15 12:20 UTC, julia-dream requested changes
Очень круто! Совсем немного совсем маленьких комментариев...

2022-04-15 12:20 UTC, julia-dream commented on src/view/components/Answers/Answers.tsx
> +            </li>
Как насчет того, чтобы вынести каждую li`шку в отдельный компонент?  туда передавать индикатор, стили нужные и тд

2022-04-15 12:20 UTC, julia-dream commented on src/view/components/Main/Main.tsx
> +  };
хм, как минимум как-нибудь так отрефакторить
`const defaultBirdData = { image: mockImage, name: mockName };`
`const bird = ( isMatch && currentLevelQuestionBird ) ?  {
    image: currentLevelQuestionBird.image,
    name: currentLevelQuestionBird.name
  } : defaultBirdData;`

2022-04-15 12:20 UTC, julia-dream commented on src/view/components/Main/Main.tsx
> +  };
а mockImage и mockName в один объект не объединяются никак?

2022-04-18 08:50 UTC, julia-dream approved these changes
Класс!

2022-04-18 09:23 UTC, merged