Testing
verenichyi/songbird pull request #2
Opened 2022-04-20 07:56 UTC by verenichyi

update dev env and dev deps

2022-04-25 11:21 UTC, julia-dream requested changes
Класс!
Оставила несколько комментариев...

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +  });
Давай разделим эти тесты каждый на несколько небольших в соответствии с общей логикой 
Для этого обычно используется describe в jest'e
здесь есть неплохое объяснение в сравнении с твоим вариантом https://stackoverflow.com/questions/32055287/what-is-the-difference-between-describe-and-it-in-jest

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +  });
Было бы замечательно, чтобы каждый it содержал в себе один, максимум два выражения expect

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    );
Подобные константы было бы неплохо вынести в отдельный объект, и, возможно, шарить между тестами

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    expect(indicator).not.toHaveClass('indicator default');
Вот здесь точно необходимо разделение на два теста - .toBeInTheDocument() и toHaveClass('indicator default');

и not.toHaveClass('indicator default'); после клика

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    expect(indicator).not.toHaveClass('indicator default');
Тесты ведь нужны нам для того, чтобы поддерживать код и вносить изменения было гораздо проще - функционал проверят именно они 
А если у тебя сломается что-то при клике, то через конкретный тест это и можно будет увидеть
В текущей ситуации - если сломается присвоение класса индикатору - тест зафейлится - тебе, как разработчику, придется проверять каждый expect  в этом тесте, чтобы понять, что конкретно ломается

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    expect(getByText(/выберите птицу из списка/i)).toBeInTheDocument();
Тоже в отдельные константы

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    const { container, getByText } = render(<App />);
В каждом тесте ты используешь render(<App />);
Такое потворение логики должно было насторожить и вызвать желание вынести это на уровень выше 
Обычно используется  
```
beforeEach(() => {
   
  });
```

2022-04-25 11:21 UTC, julia-dream commented on src/tests/app.test.tsx
> +    expect(button).not.toBeDisabled();
Аналогичную ситуацию с индикаторами описывала выше

2022-04-25 11:21 UTC, julia-dream commented on src/tests/header.test.tsx
> +import { nav } from 'src/constants/common';
По поводу общей файловой структуры - существует и такой подход, как использовал ты - конкретная папка с тестами в отдельном месте
Но, в текущей ситуации, когда приложение четко разделено на компоненты, для которых ты и используешь тесты, стоит поместить файл с тестом непосредственно в папку с компонентом 
И, соответственно, ты будешь видеть, что для каждого компонента должны быть написаны тесты в соответствии с его функционалом

2022-04-25 11:21 UTC, julia-dream commented on src/tests/header.test.tsx
> +    };
ты же не меняешь нигде initialData, эта константа может быть вынесена в принципе над блоком describe

2022-04-25 11:21 UTC, julia-dream commented on src/tests/helpers.test.ts
> +  test('Format time func should return doubled-value string', () => {
Выше оставляла ссылку, внутри блока describe лучше использовать it

2022-04-25 11:21 UTC, julia-dream commented on src/tests/helpers.test.ts
> +  test('Format time func should return doubled-value string', () => {
Классическая структура теста для такой функции: 
```
describe (Format time func)
    describe (positive scenarios)
      it 
      it
    describe (negative scenarios)
      it 
      it
```
Каждый как положительный, так и негативный сценарий должен покрывать edge cases функции, и также проверять основной функционал

2022-04-25 11:21 UTC, julia-dream commented on src/tests/helpers.test.ts
> +});
Этот файл точно нужно переписать в соответствии с комментариями выше

2022-04-27 12:05 UTC, julia-dream requested changes

2022-04-27 12:05 UTC, julia-dream commented on src/utils/helpers.test.ts
> +    });
На будущее - было бы круто для таких функций проверять самый банальный вариант 'Throw error if paarameter type isn't a number' или что-то в таком духе

2022-04-27 12:05 UTC, julia-dream commented on src/view/components/App/app.test.tsx
> +      expect(name).toBeInTheDocument();
Можем, проверим на наличие в нужном месте, а не просто в документе?

2022-04-27 12:05 UTC, julia-dream commented on src/view/components/App/app.test.tsx
> +        expect(name).toHaveTextContent(/(\*)+/gi);
регулярочку в константу

2022-04-27 12:05 UTC, julia-dream commented on src/view/components/App/app.test.tsx
> +      });
если есть notToBe, notToHave, то должна быть и положительная ситуация :)

2022-04-27 12:05 UTC, julia-dream commented on src/view/components/App/app.test.tsx
> +});
Мне казалось, мы обсуждали, что тесты стоить разделить отдельно для каждого компонента
А сейчас в одном файле и Description, и Answers и тд

2022-04-27 12:56 UTC, verenichyi commented on src/view/components/App/app.test.tsx
> +      });
так есть же :)

2022-04-28 09:37 UTC, julia-dream approved these changes

2022-04-28 11:52 UTC, merged